# Filename: train.yaml
# Path: user/config/train.yaml
# Description: 身份建模模型训练参数配置文件
# Author: msy
# Date: 2025

input_dim: 64
encoder_hidden_dim: 128
encoded_dim: 64
tcn_hidden_dim: 128
embed_dim: 128
num_classes: 10
tcn_levels: 3
kernel_size: 3

batch_size: 64
epochs: 20
learning_rate: 0.001

save_path: checkpoints/identity_model.pt
