# Filename: spectrum.yaml
# Path: inf/runner/config/plot/spectrum.yaml
# Description: 频谱图渲染模块配置文件（实时系统）
# Author: msy
# Date: 2025

# 频谱特征输入目录（由推理模块实时写入）
spectrum_input_dir: /tmp/realtime_spectrum

# 频谱图像输出目录（供前端展示、Web服务读取等）
plot_output_dir: /tmp/realtime_spectrum_plot

# Matplotlib 渲染色图方案（常见有 viridis、plasma、inferno、magma、cividis）
colormap: viridis
