# Filename: print.yaml
# Path: user/config/print.yaml
# Description: 指纹特征提取参数配置
# Author: msy
# Date: 2025

pcap_path: data/cic2017/pcap/Monday_1GB.pcap
output_csv: data/cic2017/print/Benign/Benign.csv
label: null
max_packets: None
